name: Deploy
on: [push,workflow_dispatch]
jobs:
    deploy:
         runs-on: ubuntu-latest
         steps:
             - name: Get Code
               uses: actions/checkout@v2
               #    run: |
               #    echo "Deploying code..."
               #    echo "${{toJson(github)}}"
               #    git clone https://github.com/${{github.repository}}.git 
             - name: Install Node 20
               uses: actions/setup-node@v4
               with:
                   node-version: 20
             - name: Check Version
               run: node --version
             - name: Install Dependencies
               run: npm ci  
             - name: Run Tests
               run: npm run test        

              